/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ball {
  'ballType' : BallType,
  'bowler' : string,
  'batsman' : string,
}
export type BallType = { 'noBall' : null } |
  { 'wicket' : null } |
  { 'runs' : bigint } |
  { 'wide' : null };
export interface CreateMatchArgs {
  'totalOvers' : bigint,
  'team2Name' : string,
  'team1Name' : string,
}
export interface Match {
  'status' : MatchStatus,
  'wickets1' : bigint,
  'wickets2' : bigint,
  'totalOvers' : bigint,
  'currentBowler' : string,
  'team2Name' : string,
  'isFirstInning' : boolean,
  'matchResult' : [] | [MatchResult],
  'ballsBowled' : bigint,
  'balls' : Array<Ball>,
  'requiredRunRate' : [] | [number],
  'currentBatsmen' : [string, string],
  'runRate' : number,
  'team1Name' : string,
  'sixesCount' : bigint,
}
export type MatchResult = { 'draw' : null } |
  { 'tied' : null } |
  { 'team1Won' : null } |
  { 'team2Won' : null };
export type MatchStatus = { 'completed' : null } |
  { 'ongoing' : null };
export interface _SERVICE {
  'createMatch' : ActorMethod<[CreateMatchArgs], bigint>,
  'getAllMatches' : ActorMethod<[], Array<Match>>,
  'getMatch' : ActorMethod<[bigint], Match>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];