/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreateMatchArgs = IDL.Record({
  'totalOvers' : IDL.Nat,
  'team2Name' : IDL.Text,
  'team1Name' : IDL.Text,
});
export const MatchStatus = IDL.Variant({
  'completed' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const MatchResult = IDL.Variant({
  'draw' : IDL.Null,
  'tied' : IDL.Null,
  'team1Won' : IDL.Null,
  'team2Won' : IDL.Null,
});
export const BallType = IDL.Variant({
  'noBall' : IDL.Null,
  'wicket' : IDL.Null,
  'runs' : IDL.Nat,
  'wide' : IDL.Null,
});
export const Ball = IDL.Record({
  'ballType' : BallType,
  'bowler' : IDL.Text,
  'batsman' : IDL.Text,
});
export const Match = IDL.Record({
  'status' : MatchStatus,
  'wickets1' : IDL.Nat,
  'wickets2' : IDL.Nat,
  'totalOvers' : IDL.Nat,
  'currentBowler' : IDL.Text,
  'team2Name' : IDL.Text,
  'isFirstInning' : IDL.Bool,
  'matchResult' : IDL.Opt(MatchResult),
  'ballsBowled' : IDL.Nat,
  'balls' : IDL.Vec(Ball),
  'requiredRunRate' : IDL.Opt(IDL.Float64),
  'currentBatsmen' : IDL.Tuple(IDL.Text, IDL.Text),
  'runRate' : IDL.Float64,
  'team1Name' : IDL.Text,
  'sixesCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createMatch' : IDL.Func([CreateMatchArgs], [IDL.Nat], []),
  'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getMatch' : IDL.Func([IDL.Nat], [Match], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreateMatchArgs = IDL.Record({
    'totalOvers' : IDL.Nat,
    'team2Name' : IDL.Text,
    'team1Name' : IDL.Text,
  });
  const MatchStatus = IDL.Variant({
    'completed' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const MatchResult = IDL.Variant({
    'draw' : IDL.Null,
    'tied' : IDL.Null,
    'team1Won' : IDL.Null,
    'team2Won' : IDL.Null,
  });
  const BallType = IDL.Variant({
    'noBall' : IDL.Null,
    'wicket' : IDL.Null,
    'runs' : IDL.Nat,
    'wide' : IDL.Null,
  });
  const Ball = IDL.Record({
    'ballType' : BallType,
    'bowler' : IDL.Text,
    'batsman' : IDL.Text,
  });
  const Match = IDL.Record({
    'status' : MatchStatus,
    'wickets1' : IDL.Nat,
    'wickets2' : IDL.Nat,
    'totalOvers' : IDL.Nat,
    'currentBowler' : IDL.Text,
    'team2Name' : IDL.Text,
    'isFirstInning' : IDL.Bool,
    'matchResult' : IDL.Opt(MatchResult),
    'ballsBowled' : IDL.Nat,
    'balls' : IDL.Vec(Ball),
    'requiredRunRate' : IDL.Opt(IDL.Float64),
    'currentBatsmen' : IDL.Tuple(IDL.Text, IDL.Text),
    'runRate' : IDL.Float64,
    'team1Name' : IDL.Text,
    'sixesCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'createMatch' : IDL.Func([CreateMatchArgs], [IDL.Nat], []),
    'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getMatch' : IDL.Func([IDL.Nat], [Match], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };