/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type BallType = {
    __kind__: "noBall";
    noBall: null;
} | {
    __kind__: "wicket";
    wicket: null;
} | {
    __kind__: "runs";
    runs: bigint;
} | {
    __kind__: "wide";
    wide: null;
};
export interface CreateMatchArgs {
    totalOvers: bigint;
    team2Name: string;
    team1Name: string;
}
export interface Match {
    status: MatchStatus;
    wickets1: bigint;
    wickets2: bigint;
    totalOvers: bigint;
    currentBowler: string;
    team2Name: string;
    isFirstInning: boolean;
    matchResult?: MatchResult;
    ballsBowled: bigint;
    balls: Array<Ball>;
    requiredRunRate?: number;
    currentBatsmen: [string, string];
    runRate: number;
    team1Name: string;
    sixesCount: bigint;
}
export interface Ball {
    ballType: BallType;
    bowler: string;
    batsman: string;
}
export enum MatchResult {
    draw = "draw",
    tied = "tied",
    team1Won = "team1Won",
    team2Won = "team2Won"
}
export enum MatchStatus {
    completed = "completed",
    ongoing = "ongoing"
}
export interface backendInterface {
    createMatch(args: CreateMatchArgs): Promise<bigint>;
    getAllMatches(): Promise<Array<Match>>;
    getMatch(id: bigint): Promise<Match>;
}
import type { Ball as _Ball, BallType as _BallType, Match as _Match, MatchResult as _MatchResult, MatchStatus as _MatchStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createMatch(arg0: CreateMatchArgs): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(arg0);
            return result;
        }
    }
    async getAllMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatches();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatches();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatch(arg0: bigint): Promise<Match> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_Match_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_Match_n2(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BallType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BallType): BallType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Ball_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ball): Ball {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_MatchResult_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchResult): MatchResult {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchResult]): MatchResult | null {
    return value.length === 0 ? null : from_candid_MatchResult_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ballType: _BallType;
    bowler: string;
    batsman: string;
}): {
    ballType: BallType;
    bowler: string;
    batsman: string;
} {
    return {
        ballType: from_candid_BallType_n12(_uploadFile, _downloadFile, value.ballType),
        bowler: value.bowler,
        batsman: value.batsman
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _MatchStatus;
    wickets1: bigint;
    wickets2: bigint;
    totalOvers: bigint;
    currentBowler: string;
    team2Name: string;
    isFirstInning: boolean;
    matchResult: [] | [_MatchResult];
    ballsBowled: bigint;
    balls: Array<_Ball>;
    requiredRunRate: [] | [number];
    currentBatsmen: [string, string];
    runRate: number;
    team1Name: string;
    sixesCount: bigint;
}): {
    status: MatchStatus;
    wickets1: bigint;
    wickets2: bigint;
    totalOvers: bigint;
    currentBowler: string;
    team2Name: string;
    isFirstInning: boolean;
    matchResult?: MatchResult;
    ballsBowled: bigint;
    balls: Array<Ball>;
    requiredRunRate?: number;
    currentBatsmen: [string, string];
    runRate: number;
    team1Name: string;
    sixesCount: bigint;
} {
    return {
        status: from_candid_MatchStatus_n4(_uploadFile, _downloadFile, value.status),
        wickets1: value.wickets1,
        wickets2: value.wickets2,
        totalOvers: value.totalOvers,
        currentBowler: value.currentBowler,
        team2Name: value.team2Name,
        isFirstInning: value.isFirstInning,
        matchResult: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.matchResult)),
        ballsBowled: value.ballsBowled,
        balls: from_candid_vec_n9(_uploadFile, _downloadFile, value.balls),
        requiredRunRate: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.requiredRunRate)),
        currentBatsmen: value.currentBatsmen,
        runRate: value.runRate,
        team1Name: value.team1Name,
        sixesCount: value.sixesCount
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    noBall: null;
} | {
    wicket: null;
} | {
    runs: bigint;
} | {
    wide: null;
}): {
    __kind__: "noBall";
    noBall: null;
} | {
    __kind__: "wicket";
    wicket: null;
} | {
    __kind__: "runs";
    runs: bigint;
} | {
    __kind__: "wide";
    wide: null;
} {
    return "noBall" in value ? {
        __kind__: "noBall",
        noBall: value.noBall
    } : "wicket" in value ? {
        __kind__: "wicket",
        wicket: value.wicket
    } : "runs" in value ? {
        __kind__: "runs",
        runs: value.runs
    } : "wide" in value ? {
        __kind__: "wide",
        wide: value.wide
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    ongoing: null;
}): MatchStatus {
    return "completed" in value ? MatchStatus.completed : "ongoing" in value ? MatchStatus.ongoing : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    draw: null;
} | {
    tied: null;
} | {
    team1Won: null;
} | {
    team2Won: null;
}): MatchResult {
    return "draw" in value ? MatchResult.draw : "tied" in value ? MatchResult.tied : "team1Won" in value ? MatchResult.team1Won : "team2Won" in value ? MatchResult.team2Won : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ball>): Array<Ball> {
    return value.map((x)=>from_candid_Ball_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
